# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mjui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MJ(object):
    def setupUi(self, MJ):
        MJ.setObjectName("MJ")
        MJ.resize(494, 495)
        self.label = QtWidgets.QLabel(MJ)
        self.label.setGeometry(QtCore.QRect(0, 0, 501, 121))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("lib/virtual.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(MJ)
        self.label_2.setGeometry(QtCore.QRect(30, 130, 431, 291))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("lib/mygify.gif"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(MJ)
        self.pushButton.setGeometry(QtCore.QRect(60, 420, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe Script")
        font.setPointSize(10)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton{\n"
"    \n"
"    background-color: rgb(252, 248, 191);\n"
"    border-radius: 15px;\n"
"    }\n"
"QPushButton:hover{\n"
"    \n"
"    color: rgb(255, 170, 127);\n"
"}\n"
"QPushButton:pressed{\n"
"    \n"
"    color: rgb(0, 170, 0);\n"
"}\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(MJ)
        self.pushButton_2.setGeometry(QtCore.QRect(350, 420, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe Script")
        font.setPointSize(10)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"    \n"
"    background-color: rgb(252, 248, 191);\n"
"    border-radius: 15px;\n"
"    }\n"
"QPushButton:hover{\n"
"    \n"
"    \n"
"    color: rgb(170, 0, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"    \n"
"    \n"
"    color: rgb(206, 0, 0);\n"
"}\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_3 = QtWidgets.QLabel(MJ)
        self.label_3.setGeometry(QtCore.QRect(200, 460, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("QLabel{\n"
"    \n"
"    \n"
"    background-color: rgb(170, 170, 255);\n"
"}\n"
"    ")
        self.label_3.setObjectName("label_3")

        self.retranslateUi(MJ)
        QtCore.QMetaObject.connectSlotsByName(MJ)

    def retranslateUi(self, MJ):
        _translate = QtCore.QCoreApplication.translate
        MJ.setWindowTitle(_translate("MJ", "Form"))
        self.pushButton.setText(_translate("MJ", "Start"))
        self.pushButton_2.setText(_translate("MJ", "Terminate"))
        self.label_3.setText(_translate("MJ", "@GROUP21"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MJ = QtWidgets.QWidget()
    ui = Ui_MJ()
    ui.setupUi(MJ)
    MJ.show()
    sys.exit(app.exec_())
